name: "Build Release"

# Événements sur lesquels il doit être déclenché
on:
  workflow_dispatch: # <- Manuellement
  push:         # <- Déclenché lorsque l'on pousse du code...
   branches:
     - master  # <- ... mais seulement sur cette branche

jobs:
  build: # <- Nom du job
    # runs-on: ubuntu-latest
    runs-on: k8s-builder
    steps:  
      - 
        name: "Checkout"
        uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: install etcd
        run: |
          # Install etcd and add to PATH
          # Option a) install inside kubernetes root
          hack/install-etcd.sh  # Installs in ./third_party/etcd
          echo $GITHUB_PATH
          echo "$pwd/third_party/etcd/" >> $GITHUB_PATH
          echo $GITHUB_PATH
          which etcd
      - 
        name: "Build Release Kubernetes"
        run: build/release.sh
      - 
        name: Archive Release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: k8s release
          path: |
            _output/release-tars/*.tar.gz
