name: "Build Release"

# Événements sur lesquels il doit être déclenché
on:
  workflow_dispatch: # <- Manuellement
  push:         # <- Déclenché lorsque l'on pousse du code...
   branches:
     - master  # <- ... mais seulement sur cette branche

jobs:
  build: # <- Nom du job
    # runs-on: ubuntu-latest
    runs-on: k8s-builder
    steps:  
      - 
        name: "Checkout"
        uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: install etcd
        run: |
          # Install etcd and add to PATH
          # Option a) install inside kubernetes root
          hack/install-etcd.sh  # Installs in ./third_party/etcd
          echo export PATH="\$PATH:$(pwd)/third_party/etcd" >> ~/.profile  # Add to PATH
          echo export PATH="\$PATH:$(pwd)/third_party/etcd" >> $GITHUB_PATH
          # Option b) install manually
          grep -E "image.*etcd" cluster/gce/manifests/etcd.manifest  # Find version
          # Install that version using yum/apt-get/etc
          echo export PATH="\$PATH:<LOCATION>" >> ~/.profile  # Add to PATH
          echo export PATH="\$PATH:<LOCATION>" >> $GITHUB_PATH
      - 
        name: "Build Release Kubernetes"
        run: build/release.sh

      - 
        name: Archive Release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: k8s release
          path: |
            _output/release-tars/*.tar.gz
